version: "2"

services:
  node:
    mem_limit: 300m
    memswap_limit: 1g
    build: ./nodejs/.
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      # external port | internal port
      - '3000:3000'
    volumes:
      - ./nodejs:/home/node
      - /home/node/node_modules
    links:
      - redis
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
